# Generated by Django 4.2.17 on 2025-01-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remarcableapp', '0004_alter_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='remarcableapp.tag'),
        ),
    ]
