# Generated by Django 4.2.17 on 2025-01-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remarcableapp', '0007_alter_category_name_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products', to='remarcableapp.tag'),
        ),
    ]
